spring:
  datasource:
    username: root
    password: Rikka
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.98.129
    port: 6379
    database: 0
    # 有需要可以引入lettuce连接池

  rabbitmq:
    host: 192.168.98.129
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # output full SQL
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    session:
      timeout: 1800 # time unit: s