server:
  port: 7070

spring:
  datasource:
    username: root
    password: Rikka
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false

  rabbitmq:
    host: 192.168.98.129
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://ria3cq.natappfree.cc/pay/notify
  returnUrl: http://localhost:${server.port}/

